export enum AUTH_ERROR_ENUM {
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  INVALID_SECRET = 'INVALID_SECRET',
  USER_AND_TOKEN_EMAILS_ARE_NOT_THE_SAME = 'USER_AND_TOKEN_EMAILS_ARE_NOT_THE_SAME',
}
